# Generated by Django 4.2.1 on 2023-06-21 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=7)),
                ('second_name', models.CharField(max_length=15)),
                ('phone', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=7)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
